### ISSUE TITLE
Cannot Sign In With GitHub

### ISSUE THREAD

**Issue by WandersFar** [ijprest/keyboard-layout-editor#349]
Popup just says “Signing in…” but never progresses.

**Comment by FlerkenGoose** [comment]
I also get the same, seems like there might be an issue with OAuth process, checking console I get the below:
`Uncaught SecurityError: Failed to read a named property '__oauthSuccess' from 'Window': Blocked a frame with origin "https://www.keyboard-layout-editor.com" from accessing a cross-origin frame.
    at Object.success (oauth.html?code=xxxxxxxxxxxxxxxxxxxx&state=370787.40000000596_0.4506661602379072:33:21)
    at l (jquery.min.js:4:24881)
    at Object.fireWith [as resolveWith] (jquery.min.js:4:25702)
    at k (jquery.min.js:6:4919)
    at XMLHttpRequest.<anonymous> (jquery.min.js:6:8723)`

**Comment by machineabuse** [comment]
> Popup just says “Signing in…” but never progresses.

Same issue here. Tested in Vivaldi both in regular and Incognito instances to see if cookies and/or plugins were the issue

**Comment by asa1** [comment]
Same problem here - tested in multiple browsers, and incognito mode.

**Comment by iron-viking** [comment]
Also having the same problem.

**Comment by mrnoisytiger** [comment]
+1 Having an issue as well.

**Comment by smathles** [comment]
+1. I can stay signed in from a browser that's got my credentials already there, but cannot sign in at all from either a different browser or device

**Comment by bbrfkr** [comment]
+1.

**Comment by marcoXbresciani** [comment]
Yup, same as well.
Windows with Chrome, Windows with LibreWolf.

**Comment by 3vorp** [comment]
+1, tested with Brave

**Comment by benjith17** [comment]
same issue

**Comment by ijprest** [comment]
There is no systemic issue.  The gatekeeper process is running and functional.

In the past, users have reported success by either disabling their ad-blockers, cookie-blockers, noscript extensions, etc., and/or whitelisting both of these sites in any extensions they're running:
* https://kle-gatekeeper.azurewebsites.net  (this is the gatekeeper process that handles Github logins)
* https://www.keyboard-layout-editor.com

**Comment by asa1** [comment]
I'm still encountering this problem. I've retested using the following:

- Firefox in safe mode
- Firefox in incognito mode, with exceptions added for those URLs in uBlock Origin
- Edge with no extensions installed, default browser settings
- Chromium with no extensions installed, close to default settings

**Comment by machineabuse** [comment]
> There is no systemic issue. The gatekeeper process is running and functional.
> 
> In the past, users have reported success by either disabling their ad-blockers, cookie-blockers, noscript extensions, etc., and/or whitelisting both of these sites in any extensions they're running:
> 
> * https://kle-gatekeeper.azurewebsites.net  (this is the gatekeeper process that handles Github logins)
> * https://www.keyboard-layout-editor.com

Using this information I was able to sign in after disabling the uBlock extension in FireFox, however none of the Chromium browsers I am running(Edge, Vivaldi, Brave) are able to log into KLE via GitHub regardless of the extension environment or in the case of Brave and Vivaldi; tracker and popup blocking exceptions. Tested in both regular and incognito instances.

**Comment by cedricr** [comment]
I’ve finally got it working with Firefox: after whitelisting stuff, disabling add blockers and all security features I could find in FF it still wasn’t working. But then I switched from https://keyboard-layout-editor.com/ to https://www.keyboard-layout-editor.com/, and then it worked :man_shrugging:

**Comment by asa1** [comment]
> I’ve finally got it working with Firefox: after whitelisting stuff, disabling add blockers and all security features I could find in FF it still wasn’t working. But then I switched from https://keyboard-layout-editor.com/ to https://www.keyboard-layout-editor.com/, and then it worked 🤷‍♂️

Accessing it from https://www.keyboard-layout-editor.com/ works for me too! Firefox with uBlock Origin, no changes to extensions or security settings necessary.

**Comment by gazofnaz** [comment]
I see the same error. Using the www. subdomain fixes it for me too. Perhaps the site could redirect all traffic to that subdomain?

The failing Request looks like this (I've masked out the parts that look sensitive):

```
GET /authenticate/MASKED HTTP/1.1
Host: kle-gatekeeper.azurewebsites.net
User-Agent: MASKED
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Connection: keep-alive
Cookie: ARRAffinity=MASKED
ARRAffinitySameSite=MASKED
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
If-None-Match: MASKED
Priority: u=0, i
```

Response:

```
{"error":"bad_code"}
```

**Comment by machineabuse** [comment]
> Accessing it from https://www.keyboard-layout-editor.com/ works for me too! Firefox with uBlock Origin, no changes to extensions or security settings necessary.

Can confirm that the www prefix also works in chromium based browsers!

**Comment by 3QUA9LA** [comment]
+1. When I try to sign in with GitHub, the display says "Signing in," but nothing comes up. The www prefix also works in Firefox.

**Comment by WandersFar** [comment]
OP here: Confirming I can *finally* sign in from the www domain as well!

Tested on mobile, in Brave & Firefox.

Thank you so much to everyone who discovered and confirmed this solution!

**Comment by abcdw** [comment]
@ijprest Yes, can confirm, using www subdomain also works for me. Can we add automatic redirect to it? Could be useful for people, who are not aware of this ticket. Thank you for the KLE, great project!

**Comment by kwon0408** [comment]
When using `https://keyboard-layout-editor.com` (without `www` subdomain), `GET https://kle-gatekeeper.azurewebsites.net/authenticate/<CODE>` responsed with 200 OK and its content was `{"error":"bad_code"}`. Maybe OAuth was configured working only for `https://www.keyboard-layout-editor.com` not `https://keyboard-layout-editor.com`.

Tested on Chrome 139.0.7258.140 on Windows 11.

**Comment by mkende** [comment]
@ijprest in case you missed these last comments, there seem to be a systemic issue when user reach the website through the https://keyboard-layout-editor.com addresss instead of https://www.keyboard-layout-editor.com. Maybe who gets which one depends on the browser or what they have in their history, etc. But it would certainly help a lot of people if this was fixed (maybe just with a redirection to the www version of the website).

**Comment by ijprest** [comment]
Redirect created.  Should be fixed.

**Comment by capogreco** [comment]
in Firefox with uBlock Origin disabled - trying to sign in via github in www.keyboard-layout-editor.com gives me the following error:

> An error occured during login: Gatekeeper returned an error code: bad_code

I get the same issue in Brave and a fresh installation of Chrome

using macOS 15.7.3

**Comment by WandersFar** [comment]
Yup, it's broken for me, too, again.

**Comment by thomas-maurice** [comment]
Same here :(

**Comment by rrdaud** [comment]
This should be reopened, problably as a new issue, linked to this one.
